### PR TITLE
Changes for sogo-openchange

### PR DESCRIPTION
**Pull request by papajulio**
New features
 - Added create-folder subcommand to sogo-tool to create contacts and calendar folders

Bug fixes
 - Appointment update notification mails are now sent
 - Dates stored in metadata works along TimeZone updates which fixes several
   situations such as last modified date for a folder to be returned in the right timezone.
 - Fixed reading emails from another user with same uid but from a different domain

Hello @extrafu as you can see we had to revert that three commits that you were talking about with @blaxter . For us with them the multidomain doesn't work at all for several domains. Can you review them? Thanks!

### CODE REVIEW

**Comment by extrafu** [comment]
I'm against reverting the UID / mutlidomain fixes. I asked blaxter to send me privately the SOGo configuration file + sample LDIF output that would cause issues but I haven't received the information.

**Comment by blaxter** [comment]
There are several issues with those 3 commits but to sum up and see quickly what is wrong I'll show the memcached keys created after log into sogo web app.

The scenario is as follows:
  * sogo.conf (relevant parts):
```
    SOGoEnableDomainBasedUID = YES;
    domains = {
        "foo.bar" = {
            SOGoMailDomain = foo.bar;
            SOGoUserSources = (
              {
                id = foo.bar;
                type = ldap;
                CNFieldName = cn;
                IDFieldName = cn;
                UIDFieldName = uid;
                hostname = "192.168.42.42";
                baseDN = "CN=whatever,CN=Users,DC=demo,DC=zentyal,DC=com";
                bindDN = "CN=Administrator,CN=Users,DC=demo,DC=zentyal,DC=com";
                bindPassword = "winteriscoming";
                bindFields = (sAMAccountName);
                canAuthenticate = YES;
                displayName = "Shared Addressbook";
                isAddressBook = YES;
                mapping = {
                  displayname = ("cn");
                };
              }
            );
        };

        "foo.lan" = {
            SOGoMailDomain = foo.lan;
            SOGoUserSources = (
              {
                id = foo.lan;
                type = ldap;
                CNFieldName = cn;
                IDFieldName = cn;
                UIDFieldName = uid;
                hostname = "192.168.42.42";
                baseDN = "CN=whatever2,CN=Users,DC=demo,DC=zentyal,DC=com";
                bindDN = "CN=Administrator,CN=Users,DC=demo,DC=zentyal,DC=com";
                bindPassword = "sosayweall";
                bindFields = (sAMAccountName);
                canAuthenticate = YES;
                displayName = "Shared Addressbook";
                isAddressBook = YES;
                mapping = {
                  displayname = ("cn");
                };      
              }
            );
        };
    };
```
  * Example of an user:
```
dn: CN=user0,CN=Users,CN=whatever,CN=Users,DC=demo,DC=zentyal,DC=com
objectClass: top
objectClass: posixAccount
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: user0
sn: last name
givenName: first name
instanceType: 4
whenCreated: 20150527101657.0Z
displayName: first name last name
uSNCreated: 5217
mDBStorageQuota: 10485760
name: user0
objectGUID: c6658d69-d592-4509-8fe2-b0d2166cc61a
badPwdCount: 0
codePage: 0
countryCode: 0
badPasswordTime: 0
lastLogoff: 0
lastLogon: 0
primaryGroupID: 513
objectSid: S-1-5-21-2469234688-1903108145-2559035192-1104
accountExpires: 9223372036854775807
logonCount: 0
sAMAccountName: user0@foo.bar
sAMAccountType: 805306368
userPrincipalName: user0@foo.bar
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=demo,DC=zentyal,DC=com
uid: user0
mail: user0@foo.bar
preferredLanguage: en
uidNumber: 2000
gidNumber: 1901
msExchUserAccountControl: 0
pwdLastSet: 130771954170000000
userAccountControl: 512
mailNickname: user0@foo.bar
homeMDB: CN=Mailbox Store (SAMBA),CN=First Storage Group,CN=InformationStore,C
 N=SAMBA,CN=Servers,CN=First Administrative Group,CN=Administrative Groups,CN=
 whatever,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=demo,DC=zentyal,
 DC=com
homeMTA: CN=Mailbox Store (SAMBA),CN=First Storage Group,CN=InformationStore,C
 N=SAMBA,CN=Servers,CN=First Administrative Group,CN=Administrative Groups,CN=
 whatever,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=demo,DC=zentyal,
 DC=com
legacyExchangeDN: /o=whatever/ou=First Administrative Group/cn=Recipients/cn=user
 0@foo.bar
proxyAddresses: SMTP:user0@foo.bar
proxyAddresses: =EX:/o=whatever/ou=First Administrative Group/cn=Recipients/cn=user
 0@foo.bar
proxyAddresses: X400:c=US;a= ;p=whatever;o=First Administrative Group;s=user0@foo.bar
proxyAddresses: smtp:postmaster@foo.bar
msExchRecipientTypeDetails: 6
msExchRecipientDisplayType: 0
whenChanged: 20150527101659.0Z
uSNChanged: 5321
distinguishedName: CN=user0,CN=Users,CN=whatever,CN=Users,DC=demo,DC=zentyal,
 DC=com
```
Log in as `user0@foo.bar` with inverse-inc/master, check memcached keys created:
```
user0+settings
user0@foo.bar+dn
user0@foo.bar+attributes
user0+attributes
session:x/lwJ2bpXkQbkLfqv0mBRA==
```
Log in as `user0@foo.bar`with this pull request (with the reverts), check memcached keys created:
```
user0@foo.bar+settings
user0@foo.bar+dn
session:p1hdrhtaT/8g9B/p8BiL/g==
user0@foo.bar+attributes
```
In the first case if I try to log in as `user0@foo.lan` I see `user@foo.bar` mails.

If it's working for you probably is because you are using an UIDField which is unique globally.

**Comment by extrafu** [comment]
Please try this patch:

https://github.com/inverse-inc/sogo/commit/b93cbeee26f332a07b295cbcf3699b023ebd7b1f

**Comment by papajulio** [comment]
@extrafu I've tested and is working for us. I will close this and we will merge that back in our branch and prepare another PR to pass our changes to you back. Thanks!

**Pull request closed without merging**
