### PR TITLE
Fixes for OpenChange integration

### PR DESCRIPTION
**Pull request by papajulio**
Check the NEWS file to see the fixes from the user perspective

This changes need the latest version of openchange 2.3-zentyal10 from here https://github.com/Zentyal/openchange/releases/tag/2.3-zentyal10

### CODE REVIEW

**Comment by papajulio** [comment]
Hello @extrafu when you say in #65 to update this PR, do you want me to rebase this somehow or with the two reverts it's good enough for you?

**Comment by extrafu** [comment]
I commented on PR78, not 65. For some reasons, comments appear in both.

Nonetheless, my comments were about reverting the md4 commits from the PR78 - because we just fixed that cleanly in SOGo.

**Comment by papajulio** [comment]
Ok, That's already done then :) Commits 6b3454376eee8f81f023f91dc982c5d40f48e76f and cdb608551018fe6de9696393cd4b021cfe46dd7b

**Comment by extrafu** [comment]
Perfect, we'll continue reviewing each commit. Each one that receives our blessing will have a comment "Blessed."

**Pull request merged**
