### PR TITLE
Add BLF-CRYPT password scheme support

### PR DESCRIPTION
**Pull request by the-nic**
Implement support for `BLF-CRYPT` scheme. For this scheme, the implementation is using the [openwall implementation](https://www.openwall.com/crypt/), so it will not depend on the implementation of `crypt()` in the distribution.

Fixes [#4958](https://sogo.nu/bugs/view.php?id=4958)

### CODE REVIEW

**Comment by Arvedui** [comment]
This is great! Thanks for taking care of this!

I would expect to be able to configure the parameters for bcrypt and argon2 hashes, but it seems the parameters are hard coded. Do you plan to add support for that?

**Comment by the-nic** [comment]
> I would expect to be able to configure the parameters for bcrypt and argon2 hashes, but it seems the parameters are hard coded. Do you plan to add support for that?

Not at this point. The current implementation does not really support any parameters, so I used sane defaults (following dovecot) when generating the password hash. I think they do make a lot of sense.

Also, in such a setup sogo will often not be the place to set the password, anyways - but rather over some IDM, and comparing hashes is expected to work independently of the default configuration for rounds, memory, and so on.

**Comment by Arvedui** [comment]
That is a little disappointing, but alright i will make it work for me somehow.

**Comment by the-nic** [comment]
So, I'm a bit unhappy about PBKDF2,as it requires quite new versions of openssl and gnutls. I'll have a look later again how to reduce these and make it available for more systems

**Comment by extrafu** [comment]
I also like it too much to depend on libsodium - not because it's not good, it's because it adds yet an other dependancy - which is a mess when doing packaging.

**Comment by the-nic** [comment]
> I also don't like it too much to depend on libsodium - not because it's not good, it's because it adds yet an other dependancy - which is a mess when doing packaging.

Yeah, I understand that, as I've seen the struggle with the 2fa libs, i.e. figuring out which dists support which version and so on.

From the source itself, it is still an optional addition. If libsodium is detected, it is enabled, otherwise leave it out. 

For argon2, the only other option would be to import the source of it (or another implementation). But I'd rather not copy&paste libsodium source. The maintenance of security related implementations (such as openssl, crypt(), etc) should be left to the distribution, which allows for updating the implemention system-wide. 

Also, the seemingly independent implementation (see https://github.com/P-H-C/phc-winner-argon2) is also rather large..

If you wish, I can split this up into more merge requests, ie. first blowfish, followed by the others, so that the packaging issues can be tackled separately.

**Comment by extrafu** [comment]
Yes please split them.

**Comment by the-nic** [comment]
Reduced this PR to `BLF-CRYPT` only, plus the improvements useful for other the schemes (without including them here)

**Pull request merged**
