### PR TITLE
upgrade of the idiom brazilian portuguese

### PR DESCRIPTION
**Pull request by peruchi**

### CODE REVIEW

**Comment by cgx** [comment]
Please use [Transifex](http://www.sogo.nu/english/nc/support/faq/article/how-to-translate-sogo-in-another-language.html) to submit new translations. Thank you!

**Comment by peruchi** [comment]
please would add me to accept the revisions of the Brazilian Portuguese language, as do more than three years, which are not accepted in transifex and have several translations to be improved and adjusted.
I would like to be increasingly helping the project.
Thank U.

**Comment by cgx** [comment]
Now I understand. You made *suggestions* on Transifex, but their Web interface won't allow me to view all suggestions and approve them in batch. I'm not even notified about submission of new suggestions (maybe the team coordinator does?).

Now that you are an official member of the pt_BR team, you should be able to apply your suggestions. If you do it, the next release of SOGo will integrate your changes.

Thanks and sorry for the confusion!

**Comment by peruchi** [comment]
Sorry to bother you, but I can not change a revised sentence, and possesses
several wrong sentences, would I be a coordinator of this language?

Following error: "Error:. You are not allowed to edit a revised sentence"

Atenciosamente,

Lucas Peruchi

2015-03-30 18:21 GMT-03:00 Francis Lachapelle <notifications@github.com>:

**Comment by cgx** [comment]
I promoted you as coordinator. Let me know if it gives you enough rights to change translations.

**Comment by peruchi** [comment]
Please update the Brazilian Portuguese language in this Transifex because
it was revised.

thanks You

Atenciosamente,

Lucas Peruchi

2015-03-30 21:52 GMT-03:00 Francis Lachapelle <notifications@github.com>:

**Pull request closed without merging**
