### PR TITLE
Feature #3548: Allow write to multiple contacts using 'to', 'cc' or 'bcc'

### PR DESCRIPTION
**Pull request by rfrei**
see https://sogo.nu/bugs/view.php?id=3548

### CODE REVIEW

**Comment by cgx** [comment]
That's a good idea. However, use a string instead of an integer to specify which field to use ('to', 'cc', 'bcc'). Thanks!

**Comment by rfrei** [comment]
Yes, even simpler

**Comment by rfrei** [comment]
One more question. Would it be better to choose other strings for the labels in UIxContactFoldersView.wox? According to RFC 5322 Perhaps:
'To'
'Carbon Copy (Cc)'
'Blind Carbon Copy (Bcc)'

**Comment by cgx** [comment]
I agree, you can use those strings for the menu. You'll need to add them to `UI/MailerUI/English.lproj/Localizable.strings`.

**Comment by rfrei** [comment]
Are you sure? I have add those strings to
`UI/ContactsUI/English.lproj/Localizable.strings`
`...`
`"To" = "To";`
`"CC" = "Carbon Copy (Cc)";`
`"BCC" = "Blind Carbon Copy (Bcc)";`
`...`

**Comment by cgx** [comment]
Ok, perfect! Sorry, I need some ☕️!

**Comment by rfrei** [comment]
:) good Idea!

**Comment by rfrei** [comment]
Sorry for the confusion. The english strings in
`UI/Templates/ContactsUI/UIxContactFoldersView.wox`
are now the same as in
`UI/Contacts/English.lproj/Localizable.strings`

Now it is ready I think.

**Pull request merged**
