### PR TITLE
i18n(ru): update Russian translation

### PR DESCRIPTION
**Pull request by dragoangel**
Add missing fields, fix old one

### CODE REVIEW

**Comment by dragoangel** [comment]
Sorry, found that I need to use https://www.transifex.com/, I will close this PR and help with translation over this service then?

**Comment by dragoangel** [comment]
I also found that some translations done at https://www.transifex.com/ not yet at sogo git, can I ask when\how they are imported? Thanks.

**Comment by cgx** [comment]
Yes, you need to use Transifex. We integrate the translations before each release. Thanks!

**Comment by dragoangel** [comment]
Okay, I updated Russian and Ukrainian translations on https://www.transifex.com/  :)

**Pull request closed without merging**
