### PR TITLE
added task translations to german for receipts

### PR DESCRIPTION
**Pull request by redgloboli**

### CODE REVIEW

**Comment by cgx** [comment]
Please update the translation through [Transifex](https://www.sogo.nu/support/faq/how-to-translate-sogo-in-another-language.html).

**Comment by redgloboli** [comment]
i would do it, but i can't find those 3 strings in transifex english source.

**Comment by cgx** [comment]
Good point; I've pushed the strings to Transifex. Thanks!

**Comment by redgloboli** [comment]
ok, it's translated in transifex

**Pull request closed without merging**
