### PR TITLE
i18n(kk): Add Kazakh translation by Nazym Idrissova

### PR DESCRIPTION
**Pull request by adetk**
Hello!

This is a PR with Kazakh translation. I have not touched README.md to mention Kazakh in translations section though.

Thank you!

### CODE REVIEW

**Comment by cgx** [comment]
Thank you for your contribution!

The .wod files are missing:

* SoObjects/Mailer/SOGoMailKazakhForward.wo/SOGoMailKazakhForward.wod
* SoObjects/Mailer/SOGoMailKazakhReply.wo/SOGoMailKazakhReply.wod

**Comment by adetk** [comment]
Added the missing .wod files.

**Comment by cgx** [comment]
I've pushed the strings to Transifex. That means that futur updates to the translation will need to be performed from Transifex. Please join the [Kazakh team](https://www.transifex.com/inverse/sogo/language/kk/) and I'll set your role to *coordinator*. Thanks!

**Comment by adetk** [comment]
Hi Francis,

Thank you! I've just created a TX account and joined the project's KK team.

Regards, Adet

**Pull request merged**
