### PR TITLE
Added missing TemplatesFolderName translation

### PR DESCRIPTION
**Pull request by muhyal**
Added missing TemplatesFolderName translation

### CODE REVIEW

**Comment by cgx** [comment]
Please submit your changes through [Transifex](https://www.transifex.com/inverse/sogo/). See our [FAQ](https://www.sogo.nu/support/faq/how-to-translate-sogo-in-another-language.html). Thank you!

**Comment by muhyal** [comment]
> Please submit your changes through [Transifex](https://www.transifex.com/inverse/sogo/). See our [FAQ](https://www.sogo.nu/support/faq/how-to-translate-sogo-in-another-language.html). Thank you!

Hi,

I know this, but these source translations have not been added yet on Transifex.

**Comment by cgx** [comment]
You're not searching properly:

Screen Shot 2022-05-19 at 16 12 41

**Comment by muhyal** [comment]
> You're not searching properly:
> 
> Screen Shot 2022-05-19 at 16 12 41

I'm a little careless tonight :) I edited this and many more translations on Transifex now. Please add it to the new SOGo version, thanks.

**Comment by cgx** [comment]
We only update translations when they are 100% complete:
Screen Shot 2022-05-20 at 07 49 09

**Comment by muhyal** [comment]
> We only update translations when they are 100% complete:
> Screen Shot 2022-05-20 at 07 49 09

Now I have started working to finish the 100% translation, but can you give me permission to approve the translations made?

**Pull request closed without merging**
