### PR TITLE
Convert 'configure' shebang back to /bin/sh for platform compatability

### PR DESCRIPTION
**Pull request by ethoms**

### CODE REVIEW

**Comment by ethoms** [comment]
This also needs to be applied to the master branch. If it can not be cherry picked, let me know and I will make a seperate commit and pull request for the master branch.

**Comment by waptaff** [comment]
I have no issue at all with this; merging.  Part of the reason for the change was consistency with the main SOGo library — SOPE — which uses `/bin/bash` for [its configure script](https://github.com/inverse-inc/sope/blob/master/configure); if you feel like porting that one as well, I'd gladly fast-track it into our codebase.

Thanks,

**Comment by waptaff** [comment]
Cherry-picked on master as aea4ee72c93dd468d768c1875e8b70005240685a

**Comment by ethoms** [comment]
Thanks waptaff!

I'll look into SOPE soon. I guess the SOPE FreeBSD port is already using a patch for the shebang. I'm the port maintainer, and we always like to reduce the packaging patches.

**Comment by ethoms** [comment]
It seems there is no reason 'configure' can't just use /bin/sh in SOPE. There is nothing that requires and bash features. I'll make a PR for it just now.

**Pull request merged**
